<script>
  import Header from "./Header.svelte";
  import { onMount } from 'svelte';
	import StickeyHeader from "../components/StickeyHeader.svelte";
  import bg from "../images/bg.jpg"

  const loacte = ()=>{

  }
  
  let sub = "We are looking for reinfocements for the sales!"
</script>

<div class="content" style="background-image: url('{bg}');">
  <Header/>
  <!-- <div class="cts"> -->
     <!-- <div class="gradient-overlay"></div> -->
      <!-- <img src={bg} alt="bike"> -->
  <!-- </div> -->
  <div class="info">
    <div  class="info-content">
      <p>
        <strong>velophil</strong>.
        
        Alt-Moabit 72 
        10555 Berlin 
        030 39902116 
        team@velophil.de 
      </p>
      <p>
        Verkauf: 
        Mo bis Fr 12.30 –19 
        Samstag 10 –16 
        Beratung g 
      </p>
      <p>
        Werkstatt: 
        Mo bis Fr 
        9 –11 und 14 –19 
        Samstag 10 –16 
        Derzeit nur für 
        Bestandskunden 

      </p>
    </div>
  </div>
  <a href="#overview" class="dir">
    &darr;
  </a>
</div>
<StickeyHeader/>

<style>
.content{
  height: 100dvh;
  width: 100%;
  /* background-image: linear-gradient(30deg, rgb(250, 242, 232) 14.44%, rgb(239, 230, 216) 81.18%); */
  /* position: relative; */
  margin-bottom: 5rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10rem;

  /* background-image: linear-gradient(to bottom, #15151575 , rgba(128, 128, 128, 0.59), white); */

  z-index: 200; 
}
/* .gradient-overlay {
  /* position: absolute;
  top: 0;
  left: 0; 
  width: 100%;
   height: 100%;
  background-image: linear-gradient(to bottom, rgba(22, 22, 22, 0.46) 0%, rgba(44, 43, 43, 0.59) 50%, rgba(66, 66, 66, 0.8) 100%);
  pointer-events: none;
  z-index: 1;
} */
/* .cts{
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
} */

.info{
   background-color: #f59e0b; 
  width:150px;
  height: 500px;
  padding: 1rem;
  /* position: absolute;
  top: 80px;
  left: 1255px; */
  /* z-index: 100; */


   transform: rotate(90deg); 
}
.info:hover{
  background-color: #fabe57;
}
.info-content{
  width: 140;
  font-size: 1rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 2.5rem;
}

.info-content p{
  transform: rotate(-90deg);
}
.dir{
  width: 4rem;
  height: 4rem;
  border-radius: 50%;
  border: none;
  color: #ffff;
  background-color: rgb(29, 29, 29);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 3s;
  /* position: absolute;
  top: 76%;
  right: 40%; */
  /* z-index: 100; */
  animation-name: bounce-top;
  animation-timing-function: ease-in;
  animation-duration: 2s;
  animation-iteration-count: infinite;

}

/* ----------------------------------------------
 * Generated by Animista on 2025-11-10 23:46:25
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bounce-top
 * ----------------------------------------
 */
 @-webkit-keyframes bounce-top {
  0% {
    -webkit-transform: translateY(-45px);
            transform: translateY(-45px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 1;
  }
  24% {
    opacity: 1;
  }
  40% {
    -webkit-transform: translateY(-24px);
            transform: translateY(-24px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  65% {
    -webkit-transform: translateY(-12px);
            transform: translateY(-12px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  82% {
    -webkit-transform: translateY(-6px);
            transform: translateY(-6px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  93% {
    -webkit-transform: translateY(-4px);
            transform: translateY(-4px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  25%,
  55%,
  75%,
  87% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
} 
@keyframes bounce-top {
  0% {
    -webkit-transform: translateY(-45px);
            transform: translateY(-45px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
    opacity: 1;
  }
  24% {
    opacity: 1;
  }
  40% {
    -webkit-transform: translateY(-24px);
            transform: translateY(-24px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  65% {
    -webkit-transform: translateY(-12px);
            transform: translateY(-12px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  82% {
    -webkit-transform: translateY(-6px);
            transform: translateY(-6px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  93% {
    -webkit-transform: translateY(-4px);
            transform: translateY(-4px);
    -webkit-animation-timing-function: ease-in;
            animation-timing-function: ease-in;
  }
  25%,
  55%,
  75%,
  87% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
  }
  100% {
    -webkit-transform: translateY(0px);
            transform: translateY(0px);
    -webkit-animation-timing-function: ease-out;
            animation-timing-function: ease-out;
    opacity: 1;
  }
}

</style>